#include "word_basement.h"

extern Word_Basement Base[HOW_MUCH] = {		{1,		"retain"		,	"v.保持,保留,保存"				},   
/*										*/	{2,		"executive"		,	"n.经理 adj.执行的"				},   
/*										*/	{3,		"reveal"		,	"vt.揭示"						},
/*										*/	{4,		"mature"		,	"adj.成熟的 vt.使成熟 vi.成熟"	},
/*										*/	{5,		"chase"			,	"v.追赶,驱逐 n.追逐"			},
/*										*/	{6,		"lable"			,	"n.标签，称号"					},
/*										*/	{7,		"lease"			,	"vt.租得 n.租约"				},
/*										*/	{8,		"boost"			,	"v.增加,n.提高,激励"			},
/*										*/	{9,		"rigid"			,	"adj.坚硬的,死板的"				},
/*										*/	{10,	"dismiss"		,	"v.开除,解散,摒除,不再考虑"		},
/*										*/	{11,	"inquire"		,	"v.打听,询问"					},
/*										*/	{12,	"amuse"			,	"v.使发笑"						},
/*										*/	{13,	"quit"			,	"vt.辞职 停止"					},
/*										*/	{14,	"temporary"		,	"adj.暂时的 临时的"				},
/*										*/	{15,	"scale"			,	"n.天平 磅秤,v.攀登"			},
/*										*/	{16,	"dispute"		,	"n.争端 争论 v.争议 驳斥"		},
/*										*/	{17,	"reception"		,	"n.前台 接待处"					},
/*										*/	{18,	"controversy"	,	"n.争论 辩论"					},
/*										*/	{19,	"restore"		,	"v.恢复"						},
/*										*/	{20,	"guise"			,	"n.外观 姿态 装束 伪装 v.伪装"	},
/*										*/	{21,	"liberate"		,	"v.解放 释放"					},
/*										*/	{22,	"transient"		,	"adj.短暂的 路过的 n.过客"		}
/*																									*/};